export const DISPLAY_SCREEN_FRAME_WIDTH = 1600;
export const DISPLAY_SCREEN_FRAME_HEIGHT = 600;
export const FRAME_HEADER_HEIGHT = DISPLAY_SCREEN_FRAME_HEIGHT * (10 / 100);
export const FRAME_BODY_HEIGHT = DISPLAY_SCREEN_FRAME_HEIGHT * (90 / 100);
export const FRAME_SIDE_CONTENT_HEIGHT = FRAME_BODY_HEIGHT * (85 / 100);
export const FRAME_SIDE_FOOTER_HEIGHT = FRAME_BODY_HEIGHT * (15 / 100);
