esphome:
  name: esphome-desk-display
  friendly_name: ESPHome Desk Display

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    name: "Yellow Btn"
    filters:
      - delayed_on: 50ms
  - platform: gpio
    pin:
      number: GPIO15
      inverted: true
    name: "Black Btn"
    filters:
      - delayed_on: 150ms
  - platform: gpio
    pin:
      number: GPIO16
      inverted: true
    name: "Blue Btn"
    filters:
      - delayed_on: 150ms # Use this filter to manage bounces

output:
  - platform: ledc
    pin: GPIO17 # Ton GPIO
    id: led_1_output
    inverted: false # Ajuste si nécessaire

light:
  - platform: monochromatic
    name: "LED 1"
    output: led_1_output
    id: led_1_light
    effects:
      - pulse:
          name: "Pulse"
          transition_length: 500ms
          update_interval: 500ms
      - pulse:
          name: "Pulse Slow"
          transition_length: 1500ms
          update_interval: 1500ms
      - strobe:
          name: "Blink"
          colors:
            - state: true
              duration: 500ms
            - state: false
              duration: 500ms
      - strobe:
          name: "Double Blink"
          colors:
            - state: true
              duration: 150ms
            - state: false
              duration: 150ms
            - state: true
              duration: 150ms
            - state: false
              duration: 150ms
            - state: false
              duration: 1.5s
